const tags = [
  { name: "Park" },
  { name: "Museum" },
  { name: "Restaurant" },
  { name: "Cafe" },
  { name: "Shopping Mall" },
  { name: "Hospital" },
  { name: "School" },
  { name: "University" },
  { name: "Library" },
  { name: "Gym" },
  { name: "Pharmacy" },
  { name: "Hotel" },
  { name: "Airport" },
  { name: "Train Station" },
  { name: "Bus Stop" },
  { name: "Cinema" },
  { name: "Theater" },
  { name: "Stadium" },
  { name: "Supermarket" },
  { name: "Gas Station" },
  { name: "Church" },
  { name: "Mosque" },
  { name: "Temple" },
  { name: "Bank" },
  { name: "Post Office" },
  { name: "Beach" },
  { name: "Zoo" },
  { name: "Aquarium" },
  { name: "Park and Ride" },
  { name: "Skatepark" },
  { name: "Swimming Pool" },
  { name: "Spa" },
  { name: "Amusement Park" },
  { name: "Water Park" },
  { name: "Campground" },
  { name: "Nature Reserve" },
  { name: "Golf Course" },
  { name: "Winery" },
  { name: "Good vibes" },
  { name: "Scenery" },
  { name: "Visiting place" },
  { name: "Fast foods" },
  { name: "House" },
  { name: "Coffee" },
  { name: "Breakfast" },
  { name: "Wi-Fi" },
  { name: "Vegan Options" },
  { name: "Organic" },
  { name: "Cozy Ambiance" },
  { name: "Student Discount" },
  { name: "Takeaway" },
  { name: "Pet Supplies" },
  { name: "Pet Food" },
  { name: "Toys" },
  { name: "Grooming" },
  { name: "Adoption" },
  { name: "Veterinary Services" },
  { name: "Aquariums" },
  { name: "Birds" },
  { name: "Cats" },
  { name: "Dogs" },
  { name: "Hotel" },
  { name: "Luxury" },
  { name: "Boutique" },
  { name: "Breakfast Included" },
  { name: "Free Wi-Fi" },
  { name: "Swimming Pool" },
  { name: "Business Center" },
  { name: "Pet-Friendly" },
  { name: "Room Service" },
  { name: "Groceries" },
  { name: "Fresh Produce" },
  { name: "Organic" },
  { name: "Dairy" },
  { name: "Bakery" },
  { name: "Meat" },
  { name: "Seafood" },
  { name: "Household Supplies" },
  { name: "Weekly Specials" },
  { name: "Local Products" },
  { name: "Beauty" },
  { name: "Skincare" },
  { name: "Hair Salon" },
  { name: "Nails" },
  { name: "Massage" },
  { name: "Facials" },
  { name: "Organic Products" },
  { name: "Bridal Packages" },
  { name: "Relaxing Atmosphere" },
  { name: "Fashion" },
  { name: "Apparel" },
  { name: "Accessories" },
  { name: "Men's Clothing" },
  { name: "Women's Clothing" },
  { name: "Children's Clothing" },
  { name: "Sportswear" },
  { name: "New Arrivals" },
  { name: "Sale" },
  { name: "Trendy" },
  { name: "Fine Dining" },
  { name: "International Cuisine" },
  { name: "Reservations" },
  { name: "Wine Selection" },
  { name: "Gourmet" },
  { name: "Private Dining" },
  { name: "Special Occasions" },
  { name: "Romantic" },
  { name: "Chef Specials" },
  { name: "Tasting Menu" },
  { name: "Books" },
  { name: "Literature" },
  { name: "Café" },
  { name: "New Releases" },
  { name: "Bestsellers" },
  { name: "Author Events" },
  { name: "Book Signings" },
  { name: "Cozy" },
  { name: "Reading Nook" },
  { name: "Children's Books" },
  { name: "Electronics" },
  { name: "Gadgets" },
  { name: "Accessories" },
  { name: "Smartphones" },
  { name: "Laptops" },
  { name: "Home Appliances" },
  { name: "Audio Equipment" },
  { name: "Repair Services" },
  { name: "Travel" },
  { name: "Tour" },
  
];

export default tags;
